name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # Adjusted working-directory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Clear node_modules and package-lock.json
        run: |
          rm -rf node_modules
          rm package-lock.json
      
      - name: Install dependencies
        run: npm install
      
      - name: Build and Test
        run: npm run build && npm run test

  build_crystal:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend  # Adjusted working-directory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Crystal repository
        run: |
          curl -fsSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash
      
      - name: Install Crystal
        run: sudo apt-get install -y crystal=1.0.0-1
      
      - name: Install dependencies
        run: shards install
      
      - name: Build and Test
        run: crystal spec

# Define your deployment steps below
