name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend  # Adjusted working-directory
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install dependencies
        run: npm install
      
      - name: Build and Test
        run: npm run build && npm run test
        
  build_crystal:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: path/to/crystal  # replace with the actual path to your Crystal project
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Crystal repository
        run: |
          curl -fsSL https://dist.crystal-lang.org/apt/setup.sh | sudo bash
      
      - name: Install Crystal
        run: sudo apt-get install -y crystal
      
      - name: Install dependencies
        run: shards install
      
      - name: Build and Test
        run: crystal spec
# Define your deployment steps below
